title: Core National Education Content #----> Required
remote_theme: opendocsg/opendoc-theme@v2
timezone: Asia/Singapore
repository: opendocsg/opendoc-core-national-education
plugins:
  - jekyll-include-cache
baseurl: ''
server_PROD: https://search.opendoc.sg
server_DEV: https://search-staging.opendoc.sg

fast_build: false
offline: false
preload_pages: true

hide_toolbar:
  sidebar: false
  pdf: false
  github: true
  
styling_options:
  primary_brand_color: '#C0504D' 
  logo_path: /assets/logo.png 
  opendoc_logo_path: /assets/images/logo-full.png
  feedback_url: https://form.gov.sg/5cee3d46138e3200109244df
